name: m2_cw_env
channels:
  - defaults
dependencies:
  - python=3.11
  - pre-commit
  - matplotlib
  - flake8
  - sphinx
  - black
  - pytest
  - numpy
  - pandas
  - scipy
  - pip
  - tqdm
  - ipykernel
  - pip:
      - torch
      - torchvision
      - torchmetrics
      - accelerate
      - wandb
      - pytorch-lightning
      - pytorch-lightning-bolts
      - piq
      - einops
      - torch-fidelity
