name: m2_cw
channels:
  - defaults
dependencies:
  - pre-commit
  - matplotlib
  - flake8
  - sphinx
  - black
  - pytest
  - numpy
  - pandas
  - scipy
pip:
  - torch
  - torchvision
  - wandb
  - pytorch-lightning
  - pytorch-lightning-bolts
