# General Setup.
output_dir: "./runs/blur_unet_8_orig"
wandb: true
wandb_project: "diffusion_model_cw"
seed: 42
quick_test: false # Runs training with only 1 train and val batch.
save_image_quality_metrics: true

# Training loop hyper params.
n_epoch: 50
train_batch_size: 128
val_batch_size: 512
val_fraction: 0.2

# sampling configuration.
visualise_ts: [1,5,10,100] # Time steps to visualise conditional sampling process at during validation.
num_cond_samples: 4 # number of samples to generate for conditional and uncondtional plots.

# Optimisation hyper parameters.
lr: 0.0002

# Decoder Model Configuration.
decoder_model: "unet"

# cnn decoder model params.
# decoder_model_params:
#   in_channels: 1
#   expected_shape: [28, 28]
#   n_hidden: [16, 32, 32, 16]

# UNet decoder model params.
decoder_model_params:
    dim: 8
    dim_mults: [1, 2, 4]
    channels: 1

# Diffusion model configuration.
diffusion_model: "gaussian_blur"
diffusion_model_weights: null
T: 100
noise_schedule: "const"

# linear noise schedule params.
# custom_noise_schedule_params:
#   beta_1: 0.0001
#   beta_2: 0.02

# cosine noise schedule params.
# custom_noise_schedule_params:
#   beta_max: 0.9
#   s: 0.008 # Should tuned properly according to paper... https://arxiv.org/abs/2102.09672

# constant noise schedule params.
custom_noise_schedule_params:
  beta: 1
