# General Setup.
output_dir: "./runs/q2_ddpm_unet"
wandb: false
wandb_project: "diffusion_model_cw"
seed: 42
quick_test: true # Runs training with only 1 batch.

# Training loop hyper params.
n_epoch: 50
train_batch_size: 128
val_batch_size: 512
val_fraction: 0.2

# Conditional sampling configuration.
visualise_ts: [100, 500, 1000] # Time steps to visualise conditional sampling process at during validation.
num_cond_samples: 4 # number of conditional samples to generate during validation.

# Optimisation hyper parameters.
lr: 0.0002

# Decoder Model Configuration.
decoder_model: "unet"

# cnn decoder model params.
# decoder_model_params:
#   in_channels: 1
#   expected_shape: [28, 28]
#   n_hidden: [16, 32, 32, 16]

# UNet decoder model params.
decoder_model_params:
    dim: 32
    dim_mults: [1, 2, 4]
    channels: 1

# Diffusion model configuration.
diffusion_model: "ddpm"
diffusion_model_weights: null
T: 1000
noise_schedule: "cosine"

# linear noise schedule params.
# custom_noise_schedule_params:
#   beta_1: 0.0001
#   beta_2: 0.02

# cosine noise schedule params.
custom_noise_schedule_params:
  beta_max: 0.9
  s: 0.008 # Should tune properly according to paper... https://arxiv.org/abs/2102.09672

# constant noise schedule params.
# custom_noise_schedule_params:
#   beta: 0.001
