# General Setup
output_dir: "./runs/cosine_test"
wandb: true
m2_cw: "YourProjectName"
seed: 42
quick_test: false # Runs training with only 1 batch.

# Experiment Control
n_epoch: 10
visualise_samples: "all"  # or [1, 5, 10]

# Data Handling
train_batch_size: 128
val_batch_size: 512
val_fraction: 0.2

# Model Configuration
decoder_model: "cnn"
decoder_model_params:
  in_channels: 1
  expected_shape: [28, 28]
  n_hidden: [16, 32, 32, 16]
diffusion_model: "ddpm"

noise_schedule: "const"
T: 1000

# linear noise schedule params.
# custom_noise_schedule_params:
#   beta_1: 0.0001
#   beta_2: 0.02

# cosine noise schedule params.
# custom_noise_schedule_params:
#   beta_max: 0.9 # Should tune properly according to paper... https://arxiv.org/abs/2102.09672
#   s: 0.008

# constant noise schedule params.
custom_noise_schedule_params:
  beta: 0.001

# Training Configuration
lr: 0.0002

# Data visualization
visualise_ts: [250, 500, 750, 1000]
